[workspace]
members = ["fortitude", "fortitude_macros"]
resolver = "2"

[workspace.package]
edition = "2021"
rust-version = "1.80"
repository = "https://github.com/PlasmaFAIR/fortitude"
authors = ["Liam Pattinson <liampattinson@gmail.com>"]
license = "MIT"
