[package]
name = "fortitude"
version = "0.1.0"
edition = "2021"
description = "A Fortran linter, written in Rust and with Python bindings"


[dependencies]
clap = { version = "4.4.16", features = ["derive"] }
regex = "1.10.2"
tree-sitter = "0.20.10"
walkdir = "2.4.0"

[build-dependencies]
cc = "*"
