name: Formatting

on:
  push:
    paths:
      - '**.rs'

env:
  CARGO_TERM_COLOR: always

jobs:

  format:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: format
      run: cargo fmt --check --verbose
